### PR TITLE
OSS sponsorship criteria

### PR DESCRIPTION
**Pull request by winkerVSbecks**

### CODE REVIEW

**Comment by domyen** [comment]
I think we can add some of this to the open source page [here](https://www.chromatic.com/docs/open-source/#open-source-sponsorships).

**Comment by winkerVSbecks** [comment]
@domyen  Didn't realize we had that page. I'll switch it to that page. But is the content okay?

**Review by domyen — APPROVED** [review]
This seems like the right content!

**Review by hannahpx — APPROVED** [review]
looks great to me! @winkerVSbecks

**Pull request merged**
