### PR TITLE
Clarify async nature of in-app chat

### PR DESCRIPTION
**Pull request by deandre**
We should note that chat responses are generally asynchronous rather than real-time to help manage customer expectations. 

> Responses were slow. Intercom indicated that DeAndre was online and had seen/read my responses yet responses took many hours. **If an agent is online I anticipate chat like cadence.** [emphasis mine] I understand if agents need to serve multiple customers response time is not expected to as good a DM, but this conversation was not close. Prior interactions via Intercom with other agents have been much more real time.

— [#27255108179](https://app.intercom.com/a/inbox/zj7sn9j1/inbox/conversation/27255108179)

### CODE REVIEW

**Comment by domyen** [comment]
Thanks for the PR @deandre. This doesn't really feel like a docs concern though because folks can initiate chat from anywhere on our website (not just through docs) so they'll likely never read this. 

If we want to set expectations for response time, perhaps we do that in Intercom instead. Either automatically via bot or mentioning that we're looking into it and an estimated time to answer?

For example, in the past when I was supporting customers at the end of my day, I'd mention that I was wrapping up for the day and that I'd reconnect with them in the morning. I remember most folks being quite gracious about it.

**Comment by deandre** [comment]
Thanks @domyen! I agree it's not a docs concern per se and should also be addressed in Intercom. However, because the page in question exists within docs, I wanted to open this draft PR to start a conversation around it. I don't see the harm in setting that expectation within the article if that's something we agree should be done.

**Comment by domyen** [comment]
I'd prefer to surgically meet customers where they are in the chat rather than add a disclaimer in docs before the chat even starts. The latter discourages people from chatting because in the same paragraph we say "quick turnaround time" and "beware of time delay".

I don't think docs are the place to dig into our support policy or pricing/packaging details. Our primary aim is to document how the product works, adding non-product functionality is extra stuff that we'll have to maintain over time.

**Comment by alright-fine** [comment]
@deandre I agree with @domyen here that putting this in docs feels like hedging our bets a bit too much, especially because our initial response times are solid overall. What do you think about enabling the feature in Intercom that says we typically respond _in a few hours_ or the option that gives our actual average response time, whichever gives us a bit more buffer.

**Pull request closed without merging**
