### PR TITLE
new faq - invoices

### PR DESCRIPTION
**Pull request by cgbl-90**
BizOps and support often get asked where to download the invoices. 

We could add the icon to the article or an image:
image

### CODE REVIEW

**Review by hannahpx — CHANGES_REQUESTED** [review]
I think the title should be:

How do I download previous invoices?

**Comment by winkerVSbecks** [comment]
@hannahpx isn't this already documented? https://arc.net/l/quote/lnpghgpp

**Comment by cgbl-90** [comment]
> @hannahpx isn't this already documented? https://arc.net/l/quote/lnpghgpp

**Comment by cgbl-90** [comment]
This is not documented here https://www.chromatic.com/docs/billing anywhere.

We don't show the download button in the screenshots we have of the STATEMENTS section >>
https://www.chromatic.com/docs/billing/#invoices

Maybe we could simply change the snapshot here https://www.chromatic.com/docs/billing/#invoices and add a line explaining you can download the invoice.

We do say: "Click to see a PDF of the amount owed and a breakdown of snapshot usage." But the breakdown is not the same as the invoice. It has a different format and usually customers ask for it when they lose it because of compliance issues.

@winkerVSbecks cc: @hannahpx

**Comment by winkerVSbecks** [comment]
@cgbl-90 that's the old UI. The docs use the new UI which doesn't have a download button. You click on the time period to open the usage report and then there is a big download invoice button at the bottom. The billing docs were recently updated.

CleanShot 2024-09-05 at 11 04 09@2x

**Comment by cgbl-90** [comment]
I see. Thank you! Then closing this

**Pull request closed without merging**
